"""empty message

Revision ID: b4f34c9d8fad
Revises: 6e3a44926a2e
Create Date: 2023-04-12 10:47:45.437887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f34c9d8fad'
down_revision = '6e3a44926a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('dummy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
