"""spotify refresh token

Revision ID: fc67920d06fd
Revises: b4f34c9d8fad
Create Date: 2023-04-12 13:04:36.131879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc67920d06fd'
down_revision = 'b4f34c9d8fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_refresh_token', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('spotify_refresh_token')

    # ### end Alembic commands ###
